# CoDev build/test/lint/type-check entry point. See
# docs/features/bazel-migration/design.md. Run `just` or `just --list` to
# discover recipes; every recipe is a thin, non-interactive wrapper around
# a `bazel`/`uv` command with a deterministic exit code.

default:
    @just --list

# Regenerate the Bazel pip lock from uv.lock (uv.lock stays source of truth).
# `uv export -o` also echoes the full file to stdout; silenced here.
lock:
    uv export --frozen --no-emit-project --all-extras -o requirements_lock.txt > /dev/null

build:
    bazel build //...

# Pass extra bazel test flags/targets through, e.g. `just test //tests:test_cli`.
test *args:
    bazel test //... {{args}}

lint:
    bazel run //:ruff -- check .

fmt:
    bazel run //:ruff -- format .

# Non-mutating format check, for CI.
fmt-check:
    bazel run //:ruff -- format --check .

typecheck:
    bazel run //:mypy -- --config-file=pyproject.toml src/codev_workflow tests

# Fail if requirements_lock.txt has drifted from uv.lock. Skips the
# autogenerated header's first two lines: uv embeds the literal -o path
# there, which is cosmetic and not a real drift signal.
lock-check:
    #!/usr/bin/env bash
    set -euo pipefail
    tail -n +3 requirements_lock.txt > /tmp/requirements_lock.txt.before
    uv export --frozen --no-emit-project --all-extras -o requirements_lock.txt > /dev/null
    if ! diff -q /tmp/requirements_lock.txt.before <(tail -n +3 requirements_lock.txt) > /dev/null; then
        echo "requirements_lock.txt is stale relative to uv.lock -- run 'just lock' and commit the result." >&2
        exit 1
    fi

# Everything CI's quality gate checks, in one command.
ci: lint fmt-check typecheck lock-check test
