# CoDev build/test/lint/type-check entry point. See
# docs/features/bazel-migration/design.md. Run `just` or `just --list` to
# discover recipes; every recipe is a thin, non-interactive wrapper around
# a `bazel`/`uv` command with a deterministic exit code.

default:
    @just --list

# Regenerate the Bazel pip lock from uv.lock (uv.lock stays source of truth).
# `uv export -o` also echoes the full file to stdout; silenced here.
lock:
    uv export --frozen --no-emit-project --all-extras -o requirements_lock.txt > /dev/null

build:
    bazel build //...

# Pass extra bazel test flags/targets through, e.g. `just test //tests:test_cli`.
# Runs under the default toolchain (3.13); see test-all for every supported
# version. Scoped to //tests/... rather than //... -- the root BUILD.bazel's
# ruff/mypy targets are pinned to the 3.13 pip hub and fail to even analyze
# under a --python_version override for a different hub.
test *args:
    bazel test //tests/... {{args}}

test-3-12 *args:
    bazel test --@rules_python//python/config_settings:python_version=3.12 //tests/... {{args}}

test-3-11 *args:
    bazel test --@rules_python//python/config_settings:python_version=3.11 //tests/... {{args}}

# Run the test suite under every supported Python version (3.11, 3.12, 3.13).
test-all: test test-3-12 test-3-11

lint:
    bazel run //:ruff -- check .

fmt:
    bazel run //:ruff -- format .

# Non-mutating format check, for CI.
fmt-check:
    bazel run //:ruff -- format --check .

typecheck:
    bazel run //:mypy -- --config-file=pyproject.toml src/codev_workflow tests

# Fail if requirements_lock.txt has drifted from uv.lock. Skips the
# autogenerated header's first two lines: uv embeds the literal -o path
# there, which is cosmetic and not a real drift signal.
lock-check:
    #!/usr/bin/env bash
    set -euo pipefail
    tail -n +3 requirements_lock.txt > /tmp/requirements_lock.txt.before
    uv export --frozen --no-emit-project --all-extras -o requirements_lock.txt > /dev/null
    if ! diff -q /tmp/requirements_lock.txt.before <(tail -n +3 requirements_lock.txt) > /dev/null; then
        echo "requirements_lock.txt is stale relative to uv.lock -- run 'just lock' and commit the result." >&2
        exit 1
    fi

validate-catalog:
    bazel run //scripts:validate_development_workflow -- --repo src/codev_workflow/bundle

self-test-evaluator:
    bazel run //scripts:evaluate_development_workflow -- --repo . --self-test

# Needs network access (fetches the real Claude Code CLI via npx) -- not
# part of `test`/`test-all`, which stay deterministic/offline per
# docs/architecture.md. Run manually, or see the scheduled/release-gated
# `claude-code-compat` CI job in .github/workflows/ci.yml.
verify-claude-code-compat:
    python3 scripts/verify_claude_code_compat.py

# Build the wheel via py_wheel, matched file-for-file and
# metadata-field-for-field against `python -m build`'s output (some
# metadata fields excepted -- see design.md's "PyPI Packaging"). CI's
# automated trusted-publisher job still uploads the `python -m build`
# artifact, not this one, but publish-testpypi/publish-pypi below make
# this a real, human-run publish path for the Bazel wheel.
wheel:
    bazel build //packaging:wheel

# Verify the Bazel wheel still matches python -m build's real output.
verify-wheel-parity: wheel
    #!/usr/bin/env bash
    set -euo pipefail
    rm -rf /tmp/codev-wheel-parity
    mkdir -p /tmp/codev-wheel-parity
    uv run --extra dev python -m build --outdir /tmp/codev-wheel-parity/setuptools-dist > /dev/null
    setuptools_whl=$(ls /tmp/codev-wheel-parity/setuptools-dist/*.whl)
    bazel_whl=$(bazel cquery --output=files //packaging:wheel 2>/dev/null)
    unzip -l "$setuptools_whl" | awk '{print $4}' | sed '/^$/d' | sort > /tmp/codev-wheel-parity/setuptools.manifest
    unzip -l "$bazel_whl" | awk '{print $4}' | sed '/^$/d' | sort > /tmp/codev-wheel-parity/bazel.manifest
    if ! diff -q /tmp/codev-wheel-parity/setuptools.manifest /tmp/codev-wheel-parity/bazel.manifest > /dev/null; then
        echo "Bazel wheel file manifest has diverged from python -m build's output:" >&2
        diff /tmp/codev-wheel-parity/setuptools.manifest /tmp/codev-wheel-parity/bazel.manifest >&2 || true
        exit 1
    fi
    uv run --extra dev twine check "$bazel_whl"

# Build the actual release artifact set into dist/: sdist via `python -m
# build` (py_wheel has no sdist equivalent), wheel via Bazel. This is what
# CI's `quality` job runs, so `just dist && just verify-dist` reproduces
# its release-artifact validation locally, identically -- see
# docs/features/bazel-migration/design.md's "PyPI Packaging" for why the
# swap happens instead of publishing python -m build's wheel.
dist: verify-wheel-parity
    #!/usr/bin/env bash
    set -euo pipefail
    rm -rf dist
    uv run --extra dev python -m build
    rm dist/*.whl
    cp "$(bazel cquery --output=files //packaging:wheel 2>/dev/null)" dist/

# Validate dist/ (twine check + real install + the same smoke-test
# assertion CI runs). Requires `just dist` first.
verify-dist:
    #!/usr/bin/env bash
    set -euo pipefail
    uv run --extra dev twine check dist/*
    rm -rf .release-venv
    python3 -m venv .release-venv
    .release-venv/bin/python -m pip install --no-deps dist/*.whl
    .release-venv/bin/codev --version
    .release-venv/bin/python -c "from importlib import resources; root = resources.files('codev_workflow').joinpath('bundle/.codex/agents'); assert sorted(item.name for item in root.iterdir()) == ['architecture-maintainability-specialist.toml', 'builder.toml', 'code-audit-gate.toml.template', 'code-audit.toml.template', 'concurrency-specialist.toml', 'correctness-tests-specialist.toml', 'lightweight-reviewer.toml', 'orchestrator.toml', 'outer-loop-runner.toml', 'planner.toml', 'reviewer.toml', 'rollout-specialist.toml', 'security-data-specialist.toml']"
    echo "dist/ validated: sdist + Bazel wheel, twine-clean, installs and runs correctly."

# Publish the wheel to TestPyPI. Needs TWINE_USERNAME/TWINE_PASSWORD (or an
# API token as TWINE_PASSWORD) already set in your own shell -- this recipe
# never reads, prints, or stores credentials; it only forwards your existing
# environment to rules_python's own sandboxed twine binary. Not part of
# `ci` and never run automatically. See docs/features/bazel-migration/
# design.md's "PyPI Packaging" for why this is a human-run, manual path
# separate from CI's trusted-publisher `publish` job in ci.yml.
publish-testpypi: wheel
    bazel run //packaging:wheel.publish -- --repository testpypi

# Publish the wheel to the REAL PyPI, permanently. Same credential
# requirement as publish-testpypi. There is no confirmation prompt here --
# read docs/features/bazel-migration/design.md's "PyPI Packaging" section
# before ever running this against a version that matters.
publish-pypi: wheel
    bazel run //packaging:wheel.publish -- --repository pypi

# Everything CI's quality gate checks, in one command.
ci: lint fmt-check typecheck lock-check test-all validate-catalog self-test-evaluator dist verify-dist
